<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvxprrm\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvxprrm/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVvxprrm.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVvxprrm\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVvxprrm\srcDevDebugProjectContainer([
    'container.build_hash' => 'Vvxprrm',
    'container.build_id' => '89ce3389',
    'container.build_time' => 1555018647,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvxprrm');
